name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests (stable, no features)
      run: cargo test --release
    - name: Run tests (stable, feature fnv)
      run: cargo test --release --features fnv
    - name: Run tests (stable, features fnv, bnum)
      run: cargo test --release --features bnum,fnv
    - name: Run tests (stable, feature spooky)
      run: cargo test --release --features spooky
    - name: Run tests (stable, feature xxh64)
      run: cargo test --release --features xxh64
    - name: Run tests (stable, all features except nightly)
      run: cargo test --release --features std,bnum,fnv,spooky,xxh64
    - name: Run tests (nightly, all features)
      run: rustup update nightly && cargo +nightly test --release --all-features
